# Generated by Django 2.0 on 2019-05-22 14:03

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=25, verbose_name='备注')),
                ('user', models.CharField(max_length=30, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=12, verbose_name='手机号')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('image1', stdimage.models.StdImageField(upload_to='image/%Y/%m', verbose_name='图片')),
            ],
            options={
                'verbose_name': '密码管理',
                'verbose_name_plural': '密码管理',
            },
        ),
    ]
