# Generated by Django 2.0 on 2019-05-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='标签',
            new_name='tag',
        ),
    ]
