# Generated by Django 2.0 on 2019-05-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_auto_20190527_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
