# Generated by Django 2.0 on 2019-05-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0003_auto_20190527_1746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='memo',
            old_name='tag',
            new_name='category',
        ),
    ]
