# Generated by Django 2.0 on 2019-05-27 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0004_auto_20190527_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='memo',
            options={'ordering': ['-id'], 'verbose_name': '便签', 'verbose_name_plural': '便签'},
        ),
    ]
