# Generated by Django 2.0 on 2019-06-16 13:10

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0005_auto_20190527_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='content',
            field=DjangoUeditor.models.UEditorField(verbose_name='内容'),
        ),
    ]
