# Generated by Django 2.0 on 2019-06-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0006_auto_20190616_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='title',
            field=models.TextField(default='生活', max_length=360, verbose_name='标题'),
        ),
    ]
