# Generated by Django 2.0 on 2019-05-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='姓名')),
                ('relation', models.CharField(max_length=30, verbose_name='关系')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=12, verbose_name='手机号')),
                ('word', models.CharField(max_length=50, verbose_name='职业')),
                ('sex', models.PositiveIntegerField(choices=[(1, '男'), (0, '女')], default=1, verbose_name='性别')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '联系人管理',
                'verbose_name_plural': '联系人管理',
                'ordering': ['-id'],
            },
        ),
    ]
