# Generated by Django 2.0 on 2019-05-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='colour',
            field=models.PositiveIntegerField(choices=[(0, 'primary'), (1, 'secondary'), (2, 'success'), (3, 'danger'), (4, 'warning'), (5, 'info'), (6, 'light'), (7, 'dark')], default=7, verbose_name='颜色'),
        ),
    ]
