# Generated by Django 2.0 on 2019-05-28 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='colour',
        ),
    ]
