# Generated by Django 2.0 on 2019-05-28 06:35

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('image3', stdimage.models.StdImageField(upload_to='image/%Y/%m', verbose_name='图片')),
            ],
            options={
                'verbose_name': '照片管理',
                'verbose_name_plural': '照片管理',
                'ordering': ['-id'],
            },
        ),
    ]
