# Generated by Django 2.0 on 2019-05-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('0', '工作报告'), ('1', '项目记录'), ('2', '日程安排')], default='0', max_length=20)),
                ('content', models.TextField(verbose_name='工作日报')),
                ('start_time', models.DateTimeField(default='', verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default='', verbose_name='结束时间')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '工作日报',
                'verbose_name_plural': '工作日报',
            },
        ),
    ]
