# Generated by Django 2.0 on 2019-05-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0002_auto_20190530_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='attention',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='user',
        ),
    ]
