# Generated by Django 2.0 on 2019-06-13 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0003_auto_20190530_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'verbose_name': '日程安排', 'verbose_name_plural': '日程安排'},
        ),
    ]
